services:
  app:
    image: peelregistry/peelapi:latest
    ports:
      - 3001:3000
  environment:
    - STACK=production
    - MONGO_DB_USER=${MONGO_DB_USER}
    - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
    - PORT=${PORT}
    - JWT_SECRET=${JWT_SECRET}
