services:
  app:
    image: peelregistry/peelapi:latest
    ports:
      - 3000:3000
  environment:
    - STACK=production
    - MONGO_DB_USER=${MONGO_DB_USER}
    - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
    - PORT=${PORT}
    - JWT_SECRET=${JWT_SECRET}
    - FIREBASE_TYPE=${FIREBASE_TYPE}
    - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
    - FIREBASE_PROJECT_KEY_ID=${FIREBASE_PROJECT_KEY_ID}
    - FIREBASE_PROJECT_KEY=${FIREBASE_PROJECT_KEY}
    - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
    - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
    - FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI}
    - FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI}
    - FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
    - FIREBASE_CLIENT_X509_CERT_URL=${FIREBASE_CLIENT_X509_CERT_URL}

