services:
  app:
    image: peelregistry/peel_api_dev:latest
    container_name: peel_api_dev
    ports:
      - 3000:3000
    restart: on-failure
    env_file:
      - /home/ubuntu/.env
    environment:
      - STACK=${STACK}
      - PORT=${PORT}
      - MONGO_DB_URL=${MONGO_DB_URL}
      - MONGO_DB_USER=${MONGO_DB_USER}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - FIREBASE_TYPE=${FIREBASE_TYPE}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PROJECT_KEY_ID=${FIREBASE_PROJECT_KEY_ID}
      - FIREBASE_PROJECT_KEY=${FIREBASE_PROJECT_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI}
      - FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI}
      - FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
      - FIREBASE_CLIENT_X509_CERT_URL=${FIREBASE_CLIENT_X509_CERT_URL}
      - FIREBASE_UNIVERSE_DOMAIN=${FIREBASE_UNIVERSE_DOMAIN}
