name: Build and Push Docker Image - DEVELOPMENT

on:
  push:
    branches: development
  pull_request:
    branches: development

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Docker registry
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN}}
      
      - name: Build Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          file: ./dockerfile
          tags: peelregistry/peel_api:latest

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          tag_name: v${{ github.ref }}
          release_name: Release ${{ github.run_number }} - ${{ format('YYYY-MM-JJ') }}
          body: |
            This is an automated release created by GitHub Actions.
            Commit messages:
            ${{ join(github.event.commits.*.message, '\n') }}
          draft: false
          prerelease: false