name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: peelregistry/peel_api:${{ secrets.REGISTRY_IMAGE_SHA }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN}}
      
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./dockerfile
          tags: peelregistry/peel_api:latest
          build-args: |
            MONGO_DB_USER=${{ secrets.MONGO_DB_USER }}
            MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }}
            PORT=${{ secrets.PORT }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            FIREBASE_SERVICE_ACCOUNT_KEY=${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

     
