name: Build and Push Docker Image - MAIN

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Docker registry
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN}}
      
      - name: Build Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          file: ./dockerfile
          tags: peelregistry/peel_api:latest
        
      - name: Get the SHA of the latest commit
        id: sha
        run: echo ::set-output name=sha::$(git rev-parse HEAD)

      - name: Set current date
        id: date
        run: echo ::set-output name=date::$(date +'%Y-%m-%d')

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          tag_name: ${{ github.run_number }} - ${{ github.sha }}
          release_name: Release ${{ github.run_number }} - ${{ steps.date.outputs.date }} - ${{ steps.sha.outputs.sha }}
          body: |
            This release is an automated release created by GitHub Actions.

            Commit messages:
                ${{ join(github.event.commits.*.message, '\n') }}
          draft: false
          prerelease: false